/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package activ;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ramii
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionsFrame
     */
    
    Color tmpRectColor;
    Color tmpRectColor2;
    Color tmpLineColor;
    int tmpLineWidth;
    
    public OptionsFrame() {
        initComponents();
        jlblSquareColor.setText(ImageController.squareColor.getRed()+", "+
                ImageController.squareColor.getGreen()+", "+
                ImageController.squareColor.getBlue());
        
        jlblLineColor.setText(ImageController.lineColor.getRed()+", "+
                ImageController.lineColor.getGreen()+", "+
                ImageController.lineColor.getBlue());
     
        jsLineWidth.setValue(ImageController.lineWidth);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jbtnChangeSquareColor = new javax.swing.JButton();
        jlblSquareColor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblLineColor = new javax.swing.JLabel();
        jbtnChangeLineColor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jsLineWidth = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jbtnChangeLineColor1 = new javax.swing.JButton();
        jbtnChangeSquareColor1 = new javax.swing.JButton();
        jlblSquareColor2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnClose.setText("Cancel");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jbtnChangeSquareColor.setText("Change");
        jbtnChangeSquareColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnChangeSquareColorMouseClicked(evt);
            }
        });
        jbtnChangeSquareColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeSquareColorActionPerformed(evt);
            }
        });

        jlblSquareColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSquareColor.setText("255, 255, 255");

        jLabel1.setText("Square Color :");

        jLabel2.setText("Line Color :");

        jlblLineColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLineColor.setText("255, 255, 255");

        jbtnChangeLineColor.setText("Change");
        jbtnChangeLineColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnChangeLineColorMouseClicked(evt);
            }
        });

        jLabel3.setText("Line Width :");

        jLabel4.setText("External XML :");

        jTextField1.setEditable(false);

        jbtnChangeLineColor1.setText("Change");
        jbtnChangeLineColor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnChangeLineColor1MouseClicked(evt);
            }
        });
        jbtnChangeLineColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeLineColor1ActionPerformed(evt);
            }
        });

        jbtnChangeSquareColor1.setText("Change");
        jbtnChangeSquareColor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnChangeSquareColor1MouseClicked(evt);
            }
        });
        jbtnChangeSquareColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeSquareColor1ActionPerformed(evt);
            }
        });

        jlblSquareColor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSquareColor2.setText("255, 255, 255");

        jLabel5.setText("SquareColor2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblLineColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnChangeLineColor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jsLineWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnChangeLineColor1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jlblSquareColor, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnChangeSquareColor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jlblSquareColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnChangeSquareColor1)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblSquareColor)
                    .addComponent(jbtnChangeSquareColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlblSquareColor2)
                    .addComponent(jbtnChangeSquareColor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlblLineColor)
                    .addComponent(jbtnChangeLineColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsLineWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnChangeLineColor1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnChangeSquareColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnChangeSquareColorMouseClicked
       tmpRectColor = JColorChooser.showDialog(null, "Select a color", 
               Color.YELLOW);
       jlblSquareColor.setText(tmpRectColor.getRed()+", "+
                tmpRectColor.getGreen()+", "+
                tmpRectColor.getBlue());
    }//GEN-LAST:event_jbtnChangeSquareColorMouseClicked

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* save changes */
        ImageController.squareColor = tmpRectColor;
        ImageController.squareColor2 = tmpRectColor2;
        ImageController.lineColor = tmpLineColor;
        ImageController.lineWidth = (int)jsLineWidth.getValue();
        XMLHandler.externalXML = jTextField1.getText();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnChangeLineColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnChangeLineColorMouseClicked
        tmpLineColor = JColorChooser.showDialog(null, "Select a color", 
               Color.YELLOW);
        jlblLineColor.setText(tmpLineColor.getRed()+", "+
                tmpLineColor.getGreen()+", "+
                tmpLineColor.getBlue()); 
    }//GEN-LAST:event_jbtnChangeLineColorMouseClicked

    private void jbtnChangeLineColor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnChangeLineColor1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnChangeLineColor1MouseClicked

    private void jbtnChangeLineColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeLineColor1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileFilter(new FileNameExtensionFilter("XML File", "xml"));
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            jTextField1.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jbtnChangeLineColor1ActionPerformed

    private void jbtnChangeSquareColor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnChangeSquareColor1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnChangeSquareColor1MouseClicked

    private void jbtnChangeSquareColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeSquareColor1ActionPerformed
       tmpRectColor2 = JColorChooser.showDialog(null, "Select a color", 
               Color.YELLOW);
       jlblSquareColor2.setText(tmpRectColor.getRed()+", "+
                tmpRectColor.getGreen()+", "+
                tmpRectColor.getBlue());
    }//GEN-LAST:event_jbtnChangeSquareColor1ActionPerformed

    private void jbtnChangeSquareColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeSquareColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnChangeSquareColorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnChangeLineColor;
    private javax.swing.JButton jbtnChangeLineColor1;
    private javax.swing.JButton jbtnChangeSquareColor;
    private javax.swing.JButton jbtnChangeSquareColor1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JLabel jlblLineColor;
    private javax.swing.JLabel jlblSquareColor;
    private javax.swing.JLabel jlblSquareColor2;
    private javax.swing.JSpinner jsLineWidth;
    // End of variables declaration//GEN-END:variables
}
